version: '3'

networks:
        main:
        records:
services:
        nginx:
                #image: nginx:1.20.0-alpine
                image: nginx
                container_name: nginx
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./src:/var/www
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.template
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./data/certbot/conf:/etc/letsencrypt
                        - ./data/certbot/www:/var/www/certbot
                depends_on:
                        - php
                        - mysql
                networks:
                        - main
                environment:
                        - NGINX_HOST=hta.xapik.org
                command: /bin/bash -c "envsubst '$${NGINX_HOST}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
        
        certbot:
                image: certbot/certbot
                volumes:
                    - ./data/certbot/conf:/etc/letsencrypt
                    - ./data/certbot/www:/var/www/certbot
        mysql:
                image: mysql:latest
                container_name: mysql
                restart: unless-stopped
                tty: true
                ports:
                        - "3306:3306"
                env_file:
                        - mysql.env
                volumes:
                        - mysql-data:/var/lib/mysql
                networks:
                        - main

        php:
                build:
                        context: .
                        dockerfile: ./src/Dockerfile
                container_name: php
                volumes:
                        - ./src:/var/www
                ports:
                        - "9000:9000"
                networks:
                        - main

    
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5
                ports:
                        - "8081:80"
                environment:
                        PMA_HOST: mysql
                depends_on:
                        - mysql
                networks:
                        - main

        friends:
                image: public.ecr.aws/z6p0g0b4/hta-friends:latest
                ports:
                        - "8083:8080"
                env_file:
                        - mysql.env
                environment:
                        - MYSQL_HOST=mysql
                networks:
                        - main
                depends_on:
                        - mysql

        marathon:
                image: public.ecr.aws/z6p0g0b4/hta-marathon:latest
                ports:
                        - "8084:80"
                networks:
                        - main
                depends_on:
                        - friends
                        - mysql

        googlefit:
                image: public.ecr.aws/z6p0g0b4/hta-googlefit
                ports: 
                        - "8085:3000"
                networks: 
                        - main
        records:
                image: public.ecr.aws/z6p0g0b4/hta-records:latest
                ports:
                    - "8082:8080"
                networks:
                    - main
                    - records
                depends_on:
                    - cassandradb

        cassandradb:
                image: cassandra:3
                expose:
                    - 9042
                environment:
                    - HEAP_NEWSIZE=1M
                    - MAX_HEAP_SIZE=1024M
                networks:
                    - records
                volumes:
                    - cassy-data:/var/lib/cassandra        

volumes:
        mysql-data:
        cassy-data: