version: '3'

networks:
        laravel:
services:
        nginx:
                image: nginx:1.20.0-alpine
                container_name: nginx
                ports:
                        - "8080:80"
                volumes:
                        - ./src:/var/www
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - php
                        - mysql
                networks:
                        - laravel
        mysql:
                image: mysql:latest
                container_name: mysql
                restart: unless-stopped
                tty: true
                ports:
                        - "3306:3306"
                env_file:
                        - mysql.env
                networks: 
                        - laravel
        php:
                build:
                        context: .
                        dockerfile: Dockerfile
                container_name: php
                volumes:
                        - ./src:/var/www
                ports:
                        - "9000:9000"
                networks:
                        - laravel

