version: '3'

networks:
        main:

services:
        nginx:
                #image: nginx:1.20.0-alpine
                image: nginx
                container_name: nginx
                ports:
                        - "8080:80"
                volumes:
                        - ./src:/var/www
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.template
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                depends_on:
                        - php
                        - mysql
                networks:
                        - main
                environment:
                        - NGINX_HOST=localhost
                        - NGINX_PORT=8080
                command: /bin/bash -c "envsubst '$${NGINX_HOST} $${NGINX_PORT}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 

        mysql:
                image: mysql:latest
                container_name: mysql
                restart: unless-stopped
                tty: true
                ports:
                        - "3306:3306"
                env_file:
                        - mysql.env
                volumes:
                        - mysql-data:/var/lib/mysql
                networks:
                        - main

        php:
                build:
                        context: .
                        dockerfile: ./src/Dockerfile
                container_name: php
                volumes:
                        - ./src:/var/www
                ports:
                        - "9000:9000"
                networks:
                        - main

        # PhpMyAdmin Service
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5
                ports:
                        - "8081:80"
                environment:
                        PMA_HOST: mysql
                depends_on:
                        - mysql
                networks:
                        - main

        friends:
                image: public.ecr.aws/z6p0g0b4/hta-friends:latest
                ports:
                        - "8083:8080"
                env_file:
                        - mysql.env
                environment:
                        - MYSQL_HOST=mysql
                networks:
                        - main
                depends_on:
                        - mysql

        marathon:
                build:
                        context: ./marathon
                        dockerfile: Dockerfile
                ports:
                        - "8084:80"
                networks:
                        - main
                depends_on:
                        - friends
                        - mysql

        googlefit:
                build:
                        context: ./fitnessapi
                        dockerfile: Dockerfile
                ports: 
                        - "8085:3000"
                networks: 
                        - main


volumes:
        mysql-data:
