version: "3"

networks:
  main:
  records:

services:
  records:
    build:
      context: ./records
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - main
      - records
    depends_on:
      - cassandradb

  cassandradb:
    image: cassandra:3
    expose:
      - 9042
    environment:
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M
    networks:
      - records

volumes:
  cassy-data:
