version: '3'

networks:
        main:

services:
        nginx:
                image: nginx:1.20.0-alpine
                container_name: nginx
                ports:
                        - "8080:80"
                volumes:
                        - ./src:/var/www
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - php
                        - mysql
                networks:
                        - main

        mysql:
                image: mysql:latest
                container_name: mysql
                restart: unless-stopped
                tty: true
                ports:
                        - "3306:3306"
                env_file:
                        - mysql.env
                volumes:
                        - mysql-data:/var/lib/mysql
                networks:
                        - main

        php:
                build:
                        context: .
                        dockerfile: ./src/Dockerfile
                container_name: php
                volumes:
                        - ./src:/var/www
                ports:
                        - "9000:9000"
                networks:
                        - main

        # PhpMyAdmin Service
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5
                ports:
                        - "8081:80"
                environment:
                        PMA_HOST: mysql
                depends_on:
                        - mysql
                networks:
                        - main

        friends:
                build:
                        context: ./friends
                        dockerfile: Dockerfile
                ports:
                        - "8083:8080"
                env_file:
                        - mysql.env
                environment:
                        - MYSQL_HOST=mysql
                networks:
                        - main
                depends_on:
                        - mysql

        marathon:
                build:
                        context: ./marathon
                        dockerfile: Dockerfile
                ports:
                        - "8084:80"
                networks:
                        - main
                depends_on:
                        - friends
                        - mysql


volumes:
        mysql-data:
